title: Ruby News
email: your-email@cybergizer.com

description: >- # this means to ignore newlines until "baseurl:"
  A blog for Ruby enthusiasts!

baseurl: ""
url: "https://ruby.news/"
github_username:  ruby-news

plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: assets/_sass
  style: compressed

# Pagination
paginate: 10

collections:
  top10:
    output: true

# Some default webrick headers
webrick:
  headers:
    Cache-Control: 'private,max-age=1,no-store,no-cache,post-check=0,pre-check=0'
    Cache-Control: 'age=1'
    Pragma: 'no-cache'

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
